# Generated by Django 4.1.1 on 2022-10-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(help_text='Номер комнаты', unique=True, verbose_name='Номер комнаты')),
                ('cost', models.IntegerField(default=0, help_text='Стоимость/сут.', verbose_name='Стоимость/сут.')),
                ('place_quantity', models.SmallIntegerField(help_text='Количество мест', verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'комната',
                'verbose_name_plural': 'комнаты',
            },
        ),
    ]
