# Generated by Django 4.1.1 on 2022-10-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.IntegerField(default=0, help_text='Стоимость/сут.', verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.SmallIntegerField(help_text='Номер комнаты', unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='room',
            name='place_quantity',
            field=models.SmallIntegerField(default=0, help_text='Количество мест', verbose_name='Количество мест'),
        ),
    ]
