# Generated by Django 4.1.1 on 2022-10-03 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_reserve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'verbose_name': 'бронь', 'verbose_name_plural': 'брони'},
        ),
        migrations.AddField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
