# Generated by Django 4.1.1 on 2022-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_room_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
