# Generated by Django 4.1.1 on 2022-10-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_room_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='free',
        ),
        migrations.AlterField(
            model_name='room',
            name='place_quantity',
            field=models.SmallIntegerField(default=1, help_text='Количество мест', verbose_name='Количество мест'),
        ),
    ]
