# Generated by Django 4.1.1 on 2022-10-08 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_room_free_alter_room_place_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='date',
        ),
        migrations.AddField(
            model_name='reserve',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата, ДО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата, ОТ'),
            preserve_default=False,
        ),
    ]
